### ISSUE TITLE
TO-DO before upcoming release

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/snakepipes#969]
- [ ] createIndices: drop 'gtf to files', use `gtfToGenePred` instead? (would be consistent with repoTrampoline)
- [ ] take transcript2gene.txt as input to Salmon_Alevin ("genes_t2g")
- [ ] drop gene symbol annotation from `velo_to_sce` ? (scRNAseq_splitAlevinVelocityMatrices.R) - would relieve the requirement from gene ID to gene symbol mapping
- [ ] keep `filterGTF` and all downstream functions only for counting, not for mapping steps (or disable completely?)
- [ ] create salmon indices and update organism yamls
